#GetTable2Data("H:/TasP2/Exp2_No_Sex_By_Age/","Exp2_paramsNoSexByAge_")
#GetTable2Data("H:/TasP2/Exp3_No_RR_Age/","Exp3_paramsNoRRAge_")
#GetTable2Data("H:/TasP2/Exp3_No_RR_Age_Higher_Lambda/","Exp3_paramsNoRRAge_")
#GetTable2Data("H:/TasP2/Exp9_No_Dropout/","Exp3_paramsNoDropOut_")
#GetTable2Data("H:/TasP2/Exp7_Higher_Lambda/","Exp7_paramsHigherLambda_")
#GetTable2Data("H:/TasP2/Exp6_No_Condom_Age/","Exp6_paramsNoCondomAge_")
#GetTable2Data("H:/TasP2/Exp5_Equal_Rel_Durs_Lower_Mean_Duration/","Exp4_paramsEqualRelDurs_")
#GetTable2Data("H:/TasP2/Exp5_Equal_Rel_Durs_Lower_Mean_Duration/","Exp4_paramsEqualRelDurs_")
#GetTable2Data("H:/TasP2/Exp4_No_Age_Based_Homophily_Higher_Lambda/","Exp4_paramsNoAgeHomoHigherLambda_")
#GetTable2Data("H:/TasP2/Exp4_No_Age_Based_Homophily/","Exp4_paramsNoAgeHomo_")
#GetTable2Data("H:/TasP2/Exp4_No_Age_Based_Homophily_Even_Higher_Lambda/","Exp4_paramsNoAgeHomoHigherLambda_")
#GetTable2Data("H:/TasP2/Exp40_absdiff_doubled/","Exp40_paramsAbsDiff8_")
#GetTable2Data("H:/TasP2/Exp41_absdiff_doubled_higher_lambda/","Exp40_paramsAbsDiff8_")
#GetTable2Data("H:/TasP2/Exp38_8_year_age_diff/","Exp3_params8YearAgeDiff_")
#GetTable2Data("H:/TasP2/Exp37_70_under_care/","Exp36_params70UnderCareFixed_")
#GetTable2Data("H:/TasP2/Exp36_70_under_care_higher_lambda/","Exp36_params70UnderCareFixed_higher_Lambda_")
#GetTable2Data("H:/TasP2/Exp35_50_under_care/","Exp35_params50UnderCare_")
#GetTable2Data("H:/TasP2/Exp32_60_under_care_fixed/", "Exp32_params60UnderCareFixed_")
#GetTable2Data("H:/TasP2/Exp2_No_Sex_By_Age_Higher_Prob_Sex/","Exp2_paramsNoSexByAge_")
#GetTable2Data("H:/TasP2/Exp29_N10000_60_under_care/","Exp29_paramsN10000_60_under_care_")
#GetTable2Data("H:/TasP2/Exp28_N10000_80_under_care/","Exp3_paramsN10000_80_under_care_")
#GetTable2Data("H:/TasP2/Exp27_80_under_care_fixed/","Exp3_params80UnderCareFixed_")
#GetTable2Data("H:/TasP2/Exp25_Test_Every_3_Years/","Exp25_paramsTest3Years_")
#GetTable2Data("H:/TasP2/Exp23_DropoutFixed_10perc/","Exp2_paramsDropout_10perc_")
#GetTable2Data("H:/TasP2/Exp23b_DropoutFixed_10perc_higher_lambda/","Exp23b_paramsDropout_10perc_higher_lambda_")
#GetTable2Data("H:/TasP2/","Exp1_paramsBase_")
#GetTable2Data("H:/TasP2/Exp1_Base10000_second_try/", "Exp1_paramsBase10000_")
#GetTable2Data("H:/TasP2/Exp5_Equal_Rel_Durs/","Exp4_paramsEqualRelDurs_")

#GetTable2Data("H:/TasP2/Exp43_8_year_age_diff/","Exp3_params8YearAgeDiff_")
#GetTable2Data("H:/TasP2/Exp44_absdiff_doubled_higher_lambda/","Exp40_paramsAbsDiff8_")
#GetTable2Data("H:/TasP2/Exp45_N10000_60_under_care/","Exp45_paramsN10000_60_under_care_")
#GetTable2Data("H:/TasP2/Exp46_Test_Every_3_Years/","Exp46_paramsTest3Years_")
#GetTable2Data("H:/TasP2/Exp42_N10000_80_under_care/","Exp42_paramsN10000_80_under_care_")

#GetTable2Data("H:/TasP2/Exp48_70_under_care/","Exp48_params70UnderCareFixed_")
GetTable2Data("H:/TasP2/Exp47_absdiff_doubled/","Exp47_paramsAbsDiff8_")
